# Ejercicios de Arrays y Matrices con NumPy

In [4]:
import numpy as np

## Ejercicio 1: Crear un array de 10 elementos con ceros

In [5]:
arr_ceros = np.zeros(10)
print("Array de 10 ceros:", arr_ceros)

Array de 10 ceros: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


## Ejercicio 2: Genera un array con los números del 1 al 20

In [6]:
arr_1_20 = np.arange(1, 21)
print("Array del 1 al 20:", arr_1_20)

Array del 1 al 20: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


## Ejercicio 3: Crea un array con los números pares del 2 al 50

In [7]:
arr_pares = np.arange(2, 51, 2)
print("Números pares del 2 al 50:", arr_pares)

Números pares del 2 al 50: [ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48
 50]


## Ejercicio 4: Crea una matriz identidad de 5x5

In [8]:
mat_identidad = np.eye(5)
print("Matriz identidad 5x5:")
print(mat_identidad)

Matriz identidad 5x5:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


## Ejercicio 5: Crea una matriz de 4x4 con valores aleatorios entre 0 y 1

In [9]:
mat_random = np.random.rand(4, 4)
print("Matriz 4x4 aleatoria (0 a 1):")
print(mat_random)

Matriz 4x4 aleatoria (0 a 1):
[[0.86032658 0.91212547 0.92676466 0.74865703]
 [0.60400366 0.78169586 0.52171287 0.16986865]
 [0.5042293  0.78638151 0.52908607 0.31078281]
 [0.63276412 0.5624763  0.90205853 0.75654476]]


## Ejercicio 6: Suma elemento a elemento de a=[1,2,3] y b=[4,5,6]

In [11]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
suma = a + b
print(f"a = {a}")
print(f"b = {b}")
print(f"a + b = {suma}")

a = [1 2 3]
b = [4 5 6]
a + b = [5 7 9]


## Ejercicio 7: Multiplica dos matrices 3x3 de enteros aleatorios entre 1 y 10

In [12]:
mat_a = np.random.randint(1, 11, size=(3, 3))
mat_b = np.random.randint(1, 11, size=(3, 3))
producto = mat_a @ mat_b  # equivalente a np.dot(mat_a, mat_b)

print("Matriz A:")
print(mat_a)
print("\nMatriz B:")
print(mat_b)
print("\nA × B:")
print(producto)

Matriz A:
[[ 7  1  6]
 [ 5  2 10]
 [ 9  5  2]]

Matriz B:
[[ 6  7 10]
 [10  6  3]
 [ 6  7  2]]

A × B:
[[ 88  97  85]
 [110 117  76]
 [116 107 109]]


## Ejercicio 8: Array de 15 valores aleatorios (1-100) → máximo, mínimo y promedio

In [13]:
arr_random = np.random.randint(1, 101, size=15)
print("Array:", arr_random)
print(f"Máximo:  {arr_random.max()}")
print(f"Mínimo:  {arr_random.min()}")
print(f"Promedio: {arr_random.mean():.2f}")

Array: [41 10 17 94  9 61 99 19 63 52 72 10 26 67 64]
Máximo:  99
Mínimo:  9
Promedio: 46.93


## Ejercicio 9: Matriz 5x5 con valores del 1 al 25 → extraer diagonal

In [14]:
mat_5x5 = np.arange(1, 26).reshape(5, 5)
diagonal = np.diag(mat_5x5)

print("Matriz 5x5:")
print(mat_5x5)
print(f"\nDiagonal: {diagonal}")

Matriz 5x5:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

Diagonal: [ 1  7 13 19 25]


## Ejercicio 10: Matriz 5x5 aleatoria (1-20) → suma de cada fila y columna

In [15]:
mat = np.random.randint(1, 21, size=(5, 5))
suma_filas = mat.sum(axis=1)
suma_columnas = mat.sum(axis=0)

print("Matriz:")
print(mat)
print(f"\nSuma por fila:    {suma_filas}")
print(f"Suma por columna: {suma_columnas}")

Matriz:
[[16 11  5 13 13]
 [17  2  1 19  6]
 [13  7  7  3 17]
 [12  2  3 11  8]
 [15 11  1 20 17]]

Suma por fila:    [58 45 47 36 64]
Suma por columna: [73 33 17 66 61]
